export interface UpdateUserMutation {
  foto?: []
  Nombres?: string;
  Apellidos?: string;
  Compania?: string;
  Cedula_Ruc?: number;
  Profesion?: string;
  Pasaporte?: string;
  Sexo: string
  Fecha_nacimiento: string
  Discapacidad: string
  Usuario?: string
  tipo_de_sangre: string
  Nacionalidad: string
  Estado_Civil: string
  Carga_Civil: string
  Celular: number
  Telefono_Convencional: number
  Correo: string
  Correo_Alternativo: string
  Coordinador?: string
  Cedula_Coordinador?: number
  Tipo_de_Proyecto: string
  Tipo_de_Servicio: string
  Ocupacion: string
  Fecha_de_Ingreso_a_la_Organizacion: string
  Pais: string
  Ciudad: string
  Corregimiento: string
  Provincia: string
  Departamento: string
  Canton: string
  Domicilio1: string
  Domicilio2: string
  Casa: string
  Pasaje: string
  Codigo_Postal: string
  Valor_del_Contrato?: number
  Valor_Adendum?: number
  Valor_Cheque?: number
  Acta_de_Adelanto?: number
  Acta_de_Finiquito?: number
  Acta_Compromiso_Pago?: number
  Contrato_de_Privado_de_Gestion_e_numberermediacion?: number
  Pagare?: number
  Valor_letra_de_Cambio?: number
  Bono_Eficiencia_Cumplimiento?: number
  Convenio_Compensacion?: number
  Certificado_de_Garantia_y_Depositos?: number
  Numero_del_Contrato?: number
  Declaracion_Jurada: string
  Numero_de_Cuenta: number
  Banco_Cooperativa: string
  Tipo_de_Cuenta3: string
  Numero_Cuenta2: number
  Banco_Cooperativa2: string
  Tipo_de_Cuenta2: string
  Numero_de_Cuenta3: number
  Banco_Cooperativa3: string
  Tipo_de_Cuenta: string
  Beneficiario1: string
  Cedula_Beneficiario1: number
  Pasaporte_Beneficiario1: string
  Nacimiento_Beneficiario1: string
  Nacionalidad_Beneficiario1: string
  Sexo_Beneficiario1: string
  Parentezco_Beneficiario1: string
  Edad_Beneficiario1: string
  Celular_Beneficiario1: number
  Telefono_Convencional_Beneficiario1: number
  Email_Beneficiario1: string
  Domicilio_Beneficiario1: string
  Beneficiario2: string
  Cedula_Beneficiario2: number
  Pasaporte_Beneficiario2: string
  Nacimiento_Beneficiario2: string
  Nacionalidad_Beneficiario2: string
  Sexo_Beneficiario2: string
  Parentezco_Beneficiario2: string
  Edad_Beneficiario2: string
  Celular_Beneficiario2: number
  Telefono_Convencional_Beneficiario2: number
  Email_Beneficiario2: string
  Domicilio_Beneficiario2: string
  Beneficiario3: string
  Cedula_Beneficiario3: number
  Pasaporte_Beneficiario3: string
  Nacimiento_Beneficiario3: string
  Nacionalidad_Beneficiario3: string
  Sexo_Beneficiario3: string
  Parentezco_Beneficiario3: string
  Edad_Beneficiario3: string
  Celular_Beneficiario3: number
  Telefono_Convencional_Beneficiario3: number
  Email_Beneficiario3: string
  Domicilio_Beneficiario3: string
  Estatus?: string
  Contrato_de_Confidencialidad?: []
  Lectura_Biometrica?: string
  Contrato_Privado?: []
  Solicitudes_de_Bancos?: []
  Contrato_Especial?: []
  Cheques?: []
  Comprimiso_Letra_de_Cambio?: []
  Formularios?: []
  Notarias_Autorizadas_con_Declaraciones_Juradas?: []
  Cotizaciones?: []
  Acta_Compromiso_Pago_Doc?: []
  Ficha_Tecnica?: []
  Acta_de_Finiquito_Doc?: []
  Aportaciones?: []
  Cedulas_Doc?: []
  Adendum?: []
  Pasaportes_Doc?: []
  Aporte_numberernacional?: []
  Fidecomisos?: []
  Apostillamientos?: []
  Pagares_Doc?: []
  Covenio_de_Compensacion?: []
  Contrato_de_Gestion_e_numberermediacion?: []
  Cedula_de_Beneficiarios_Doc?: []
  Jubilacion: string
  published_at?: string
  created_by?: string
  upstringd_by?: string
}
