
interface _GlobalComponents {
      'CompanyCard': typeof import("../components/CompanyCard.vue")['default']
    'CountdownTimer': typeof import("../components/CountdownTimer.vue")['default']
    'FormularioColumna': typeof import("../components/FormularioColumna.vue")['default']
    'FormularioColumnaLanding': typeof import("../components/FormularioColumnaLanding.vue")['default']
    'FormularioColumnaModificaPlanes': typeof import("../components/FormularioColumnaModificaPlanes.vue")['default']
    'FormularioSoporte': typeof import("../components/FormularioSoporte.vue")['default']
    'ImageLinks': typeof import("../components/ImageLinks.vue")['default']
    'ImageSlider': typeof import("../components/ImageSlider.vue")['default']
    'ImageSliderfoot': typeof import("../components/ImageSliderfoot.vue")['default']
    'ImagenColumna': typeof import("../components/ImagenColumna.vue")['default']
    'ImagenSoporte': typeof import("../components/ImagenSoporte.vue")['default']
    'Loading': typeof import("../components/Loading.vue")['default']
    'PinnedCard': typeof import("../components/PinnedCard.vue")['default']
    'VideoPopup': typeof import("../components/VideoPopup.vue")['default']
    'CartItems': typeof import("../components/cart/CartItems.vue")['default']
    'CartCheckoutCard': typeof import("../components/cart/CheckoutCard.vue")['default']
    'CartCupon': typeof import("../components/cart/Cupon.vue")['default']
    'CartForm': typeof import("../components/cart/Form.vue")['default']
    'CartPaypal': typeof import("../components/cart/Paypal.vue")['default']
    'CartPriceCard': typeof import("../components/cart/PriceCard.vue")['default']
    'CartSecurityCard': typeof import("../components/cart/SecurityCard.vue")['default']
    'CommonCalenderAppoinment': typeof import("../components/common/CalenderAppoinment.vue")['default']
    'CommonDateModal': typeof import("../components/common/DateModal.vue")['default']
    'CommonButtonsBaseButton': typeof import("../components/common/buttons/base-button.vue")['default']
    'CommonButtonsScrollTop': typeof import("../components/common/buttons/scroll-top.vue")['default']
    'CommonInputsBaseInput': typeof import("../components/common/inputs/base-input.vue")['default']
    'CommonInputsBaseSelect': typeof import("../components/common/inputs/base-select.vue")['default']
    'CommonInputsBaseTextarea': typeof import("../components/common/inputs/base-textarea.vue")['default']
    'CommonInputsFileInputExtended': typeof import("../components/common/inputs/file-input-extended.vue")['default']
    'CommonInputsFileInputImageWebcam': typeof import("../components/common/inputs/file-input-image-webcam.vue")['default']
    'CommonInputsFileInput': typeof import("../components/common/inputs/file-input.vue")['default']
    'CommonPaginationBottomPagination': typeof import("../components/common/pagination/bottom-pagination.vue")['default']
    'InputsBaseInput': typeof import("../components/inputs/base-input.vue")['default']
    'InputsBaseSelect': typeof import("../components/inputs/base-select.vue")['default']
    'InputsBaseTextarea': typeof import("../components/inputs/base-textarea.vue")['default']
    'InputsFileInputExtended': typeof import("../components/inputs/file-input-extended.vue")['default']
    'InputsFileInputImageWebcam': typeof import("../components/inputs/file-input-image-webcam.vue")['default']
    'InputsFileInput': typeof import("../components/inputs/file-input.vue")['default']
    'LoginAccountNotExistModal': typeof import("../components/login/AccountNotExistModal.vue")['default']
    'LoginLoader': typeof import("../components/login/Loader.vue")['default']
    'Lottie': typeof import("../components/lottie.vue")['default']
    'NavBar': typeof import("../components/navBar.vue")['default']
    'UiFooter': typeof import("../components/ui/footer.vue")['default']
    'UiHeader': typeof import("../components/ui/header.vue")['default']
    'UiSlider': typeof import("../components/ui/slider.vue")['default']
    'ViewsLandingLanderSlider': typeof import("../components/views/landing/LanderSlider.vue")['default']
    'ViewsLandingScrollSection': typeof import("../components/views/landing/ScrollSection.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'SwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyCompanyCard': typeof import("../components/CompanyCard.vue")['default']
    'LazyCountdownTimer': typeof import("../components/CountdownTimer.vue")['default']
    'LazyFormularioColumna': typeof import("../components/FormularioColumna.vue")['default']
    'LazyFormularioColumnaLanding': typeof import("../components/FormularioColumnaLanding.vue")['default']
    'LazyFormularioColumnaModificaPlanes': typeof import("../components/FormularioColumnaModificaPlanes.vue")['default']
    'LazyFormularioSoporte': typeof import("../components/FormularioSoporte.vue")['default']
    'LazyImageLinks': typeof import("../components/ImageLinks.vue")['default']
    'LazyImageSlider': typeof import("../components/ImageSlider.vue")['default']
    'LazyImageSliderfoot': typeof import("../components/ImageSliderfoot.vue")['default']
    'LazyImagenColumna': typeof import("../components/ImagenColumna.vue")['default']
    'LazyImagenSoporte': typeof import("../components/ImagenSoporte.vue")['default']
    'LazyLoading': typeof import("../components/Loading.vue")['default']
    'LazyPinnedCard': typeof import("../components/PinnedCard.vue")['default']
    'LazyVideoPopup': typeof import("../components/VideoPopup.vue")['default']
    'LazyCartItems': typeof import("../components/cart/CartItems.vue")['default']
    'LazyCartCheckoutCard': typeof import("../components/cart/CheckoutCard.vue")['default']
    'LazyCartCupon': typeof import("../components/cart/Cupon.vue")['default']
    'LazyCartForm': typeof import("../components/cart/Form.vue")['default']
    'LazyCartPaypal': typeof import("../components/cart/Paypal.vue")['default']
    'LazyCartPriceCard': typeof import("../components/cart/PriceCard.vue")['default']
    'LazyCartSecurityCard': typeof import("../components/cart/SecurityCard.vue")['default']
    'LazyCommonCalenderAppoinment': typeof import("../components/common/CalenderAppoinment.vue")['default']
    'LazyCommonDateModal': typeof import("../components/common/DateModal.vue")['default']
    'LazyCommonButtonsBaseButton': typeof import("../components/common/buttons/base-button.vue")['default']
    'LazyCommonButtonsScrollTop': typeof import("../components/common/buttons/scroll-top.vue")['default']
    'LazyCommonInputsBaseInput': typeof import("../components/common/inputs/base-input.vue")['default']
    'LazyCommonInputsBaseSelect': typeof import("../components/common/inputs/base-select.vue")['default']
    'LazyCommonInputsBaseTextarea': typeof import("../components/common/inputs/base-textarea.vue")['default']
    'LazyCommonInputsFileInputExtended': typeof import("../components/common/inputs/file-input-extended.vue")['default']
    'LazyCommonInputsFileInputImageWebcam': typeof import("../components/common/inputs/file-input-image-webcam.vue")['default']
    'LazyCommonInputsFileInput': typeof import("../components/common/inputs/file-input.vue")['default']
    'LazyCommonPaginationBottomPagination': typeof import("../components/common/pagination/bottom-pagination.vue")['default']
    'LazyInputsBaseInput': typeof import("../components/inputs/base-input.vue")['default']
    'LazyInputsBaseSelect': typeof import("../components/inputs/base-select.vue")['default']
    'LazyInputsBaseTextarea': typeof import("../components/inputs/base-textarea.vue")['default']
    'LazyInputsFileInputExtended': typeof import("../components/inputs/file-input-extended.vue")['default']
    'LazyInputsFileInputImageWebcam': typeof import("../components/inputs/file-input-image-webcam.vue")['default']
    'LazyInputsFileInput': typeof import("../components/inputs/file-input.vue")['default']
    'LazyLoginAccountNotExistModal': typeof import("../components/login/AccountNotExistModal.vue")['default']
    'LazyLoginLoader': typeof import("../components/login/Loader.vue")['default']
    'LazyLottie': typeof import("../components/lottie.vue")['default']
    'LazyNavBar': typeof import("../components/navBar.vue")['default']
    'LazyUiFooter': typeof import("../components/ui/footer.vue")['default']
    'LazyUiHeader': typeof import("../components/ui/header.vue")['default']
    'LazyUiSlider': typeof import("../components/ui/slider.vue")['default']
    'LazyViewsLandingLanderSlider': typeof import("../components/views/landing/LanderSlider.vue")['default']
    'LazyViewsLandingScrollSection': typeof import("../components/views/landing/ScrollSection.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtLinkLocale': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
    'LazySwitchLocalePathLink': typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const CompanyCard: typeof import("../components/CompanyCard.vue")['default']
export const CountdownTimer: typeof import("../components/CountdownTimer.vue")['default']
export const FormularioColumna: typeof import("../components/FormularioColumna.vue")['default']
export const FormularioColumnaLanding: typeof import("../components/FormularioColumnaLanding.vue")['default']
export const FormularioColumnaModificaPlanes: typeof import("../components/FormularioColumnaModificaPlanes.vue")['default']
export const FormularioSoporte: typeof import("../components/FormularioSoporte.vue")['default']
export const ImageLinks: typeof import("../components/ImageLinks.vue")['default']
export const ImageSlider: typeof import("../components/ImageSlider.vue")['default']
export const ImageSliderfoot: typeof import("../components/ImageSliderfoot.vue")['default']
export const ImagenColumna: typeof import("../components/ImagenColumna.vue")['default']
export const ImagenSoporte: typeof import("../components/ImagenSoporte.vue")['default']
export const Loading: typeof import("../components/Loading.vue")['default']
export const PinnedCard: typeof import("../components/PinnedCard.vue")['default']
export const VideoPopup: typeof import("../components/VideoPopup.vue")['default']
export const CartItems: typeof import("../components/cart/CartItems.vue")['default']
export const CartCheckoutCard: typeof import("../components/cart/CheckoutCard.vue")['default']
export const CartCupon: typeof import("../components/cart/Cupon.vue")['default']
export const CartForm: typeof import("../components/cart/Form.vue")['default']
export const CartPaypal: typeof import("../components/cart/Paypal.vue")['default']
export const CartPriceCard: typeof import("../components/cart/PriceCard.vue")['default']
export const CartSecurityCard: typeof import("../components/cart/SecurityCard.vue")['default']
export const CommonCalenderAppoinment: typeof import("../components/common/CalenderAppoinment.vue")['default']
export const CommonDateModal: typeof import("../components/common/DateModal.vue")['default']
export const CommonButtonsBaseButton: typeof import("../components/common/buttons/base-button.vue")['default']
export const CommonButtonsScrollTop: typeof import("../components/common/buttons/scroll-top.vue")['default']
export const CommonInputsBaseInput: typeof import("../components/common/inputs/base-input.vue")['default']
export const CommonInputsBaseSelect: typeof import("../components/common/inputs/base-select.vue")['default']
export const CommonInputsBaseTextarea: typeof import("../components/common/inputs/base-textarea.vue")['default']
export const CommonInputsFileInputExtended: typeof import("../components/common/inputs/file-input-extended.vue")['default']
export const CommonInputsFileInputImageWebcam: typeof import("../components/common/inputs/file-input-image-webcam.vue")['default']
export const CommonInputsFileInput: typeof import("../components/common/inputs/file-input.vue")['default']
export const CommonPaginationBottomPagination: typeof import("../components/common/pagination/bottom-pagination.vue")['default']
export const InputsBaseInput: typeof import("../components/inputs/base-input.vue")['default']
export const InputsBaseSelect: typeof import("../components/inputs/base-select.vue")['default']
export const InputsBaseTextarea: typeof import("../components/inputs/base-textarea.vue")['default']
export const InputsFileInputExtended: typeof import("../components/inputs/file-input-extended.vue")['default']
export const InputsFileInputImageWebcam: typeof import("../components/inputs/file-input-image-webcam.vue")['default']
export const InputsFileInput: typeof import("../components/inputs/file-input.vue")['default']
export const LoginAccountNotExistModal: typeof import("../components/login/AccountNotExistModal.vue")['default']
export const LoginLoader: typeof import("../components/login/Loader.vue")['default']
export const Lottie: typeof import("../components/lottie.vue")['default']
export const NavBar: typeof import("../components/navBar.vue")['default']
export const UiFooter: typeof import("../components/ui/footer.vue")['default']
export const UiHeader: typeof import("../components/ui/header.vue")['default']
export const UiSlider: typeof import("../components/ui/slider.vue")['default']
export const ViewsLandingLanderSlider: typeof import("../components/views/landing/LanderSlider.vue")['default']
export const ViewsLandingScrollSection: typeof import("../components/views/landing/ScrollSection.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyCompanyCard: typeof import("../components/CompanyCard.vue")['default']
export const LazyCountdownTimer: typeof import("../components/CountdownTimer.vue")['default']
export const LazyFormularioColumna: typeof import("../components/FormularioColumna.vue")['default']
export const LazyFormularioColumnaLanding: typeof import("../components/FormularioColumnaLanding.vue")['default']
export const LazyFormularioColumnaModificaPlanes: typeof import("../components/FormularioColumnaModificaPlanes.vue")['default']
export const LazyFormularioSoporte: typeof import("../components/FormularioSoporte.vue")['default']
export const LazyImageLinks: typeof import("../components/ImageLinks.vue")['default']
export const LazyImageSlider: typeof import("../components/ImageSlider.vue")['default']
export const LazyImageSliderfoot: typeof import("../components/ImageSliderfoot.vue")['default']
export const LazyImagenColumna: typeof import("../components/ImagenColumna.vue")['default']
export const LazyImagenSoporte: typeof import("../components/ImagenSoporte.vue")['default']
export const LazyLoading: typeof import("../components/Loading.vue")['default']
export const LazyPinnedCard: typeof import("../components/PinnedCard.vue")['default']
export const LazyVideoPopup: typeof import("../components/VideoPopup.vue")['default']
export const LazyCartItems: typeof import("../components/cart/CartItems.vue")['default']
export const LazyCartCheckoutCard: typeof import("../components/cart/CheckoutCard.vue")['default']
export const LazyCartCupon: typeof import("../components/cart/Cupon.vue")['default']
export const LazyCartForm: typeof import("../components/cart/Form.vue")['default']
export const LazyCartPaypal: typeof import("../components/cart/Paypal.vue")['default']
export const LazyCartPriceCard: typeof import("../components/cart/PriceCard.vue")['default']
export const LazyCartSecurityCard: typeof import("../components/cart/SecurityCard.vue")['default']
export const LazyCommonCalenderAppoinment: typeof import("../components/common/CalenderAppoinment.vue")['default']
export const LazyCommonDateModal: typeof import("../components/common/DateModal.vue")['default']
export const LazyCommonButtonsBaseButton: typeof import("../components/common/buttons/base-button.vue")['default']
export const LazyCommonButtonsScrollTop: typeof import("../components/common/buttons/scroll-top.vue")['default']
export const LazyCommonInputsBaseInput: typeof import("../components/common/inputs/base-input.vue")['default']
export const LazyCommonInputsBaseSelect: typeof import("../components/common/inputs/base-select.vue")['default']
export const LazyCommonInputsBaseTextarea: typeof import("../components/common/inputs/base-textarea.vue")['default']
export const LazyCommonInputsFileInputExtended: typeof import("../components/common/inputs/file-input-extended.vue")['default']
export const LazyCommonInputsFileInputImageWebcam: typeof import("../components/common/inputs/file-input-image-webcam.vue")['default']
export const LazyCommonInputsFileInput: typeof import("../components/common/inputs/file-input.vue")['default']
export const LazyCommonPaginationBottomPagination: typeof import("../components/common/pagination/bottom-pagination.vue")['default']
export const LazyInputsBaseInput: typeof import("../components/inputs/base-input.vue")['default']
export const LazyInputsBaseSelect: typeof import("../components/inputs/base-select.vue")['default']
export const LazyInputsBaseTextarea: typeof import("../components/inputs/base-textarea.vue")['default']
export const LazyInputsFileInputExtended: typeof import("../components/inputs/file-input-extended.vue")['default']
export const LazyInputsFileInputImageWebcam: typeof import("../components/inputs/file-input-image-webcam.vue")['default']
export const LazyInputsFileInput: typeof import("../components/inputs/file-input.vue")['default']
export const LazyLoginAccountNotExistModal: typeof import("../components/login/AccountNotExistModal.vue")['default']
export const LazyLoginLoader: typeof import("../components/login/Loader.vue")['default']
export const LazyLottie: typeof import("../components/lottie.vue")['default']
export const LazyNavBar: typeof import("../components/navBar.vue")['default']
export const LazyUiFooter: typeof import("../components/ui/footer.vue")['default']
export const LazyUiHeader: typeof import("../components/ui/header.vue")['default']
export const LazyUiSlider: typeof import("../components/ui/slider.vue")['default']
export const LazyViewsLandingLanderSlider: typeof import("../components/views/landing/LanderSlider.vue")['default']
export const LazyViewsLandingScrollSection: typeof import("../components/views/landing/ScrollSection.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const LazySwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
